// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqtsqzaqxajztfzwomxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxdHNxemFxeGFqenRmendvbXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTM1MzAsImV4cCI6MjA2MDU4OTUzMH0.7iQWKqlPk_cjJqDDWmXE8Bx-XIL7odleBZik5YI2wR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);